import Head from 'next/head'
import Layout from '../components/layout'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <>
            <Head>
                <title>Salus</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Layout>
                <div className={styles.container}>


                    <div className="container text-center">
                        <h1>Welcome to Salus</h1>
                    </div>
                </div>
            </Layout>
        </>


    )
}
